const cheerio = require('cheerio')
const fs = require('fs')

const Util = require('topseed-utils')
const U = new Util()

require('@skatejs/ssr/register')
const render = require('@skatejs/ssr')

class SR {

	renderComp(compFile, Comp, comp, $page, initFn){
		return new Promise(function (resolve, reject){
	
			global.$ = U.getAsDoc(compFile)
				
			//copy attributes
			var comptag = $page(Comp.is).get(0) //one component with this name per page
			for (var name in comptag.attribs) { //cheerio
				comp.setAttribute(name, comptag.attribs[name])
			}
	
			var p = Promise.resolve()
			p.then(function(){
				if (initFn)
					return initFn()
				else
					return Promise.resolve()
			})
			.then(function(){
				//skatejs/ssr, 
				//https://medium.com/@treshugart/%C3%A5server-side-rendering-web-components-e5df705f3f48
				return render(comp, {rehydrate: false})
			})
			.then(function(renderResult){
				var $comp = cheerio.load(renderResult)
				//need to copy css to shadow dom during rehydration, replace id generated by skatejs
				var styleId = '__style_'+Comp.is
				$comp('style').first().attr('id', styleId)
				$comp(Comp.is).attr('data-style-id', styleId)
	
				//replace el in page
				$page(Comp.is).replaceWith($comp.html())
	
				return Promise.resolve()
			}).then(resolve)
		})
	}
}

module.exports = SR